/**
 * File contains the code to update the pokemon.json file
 */


//Libraries
const fs = require("fs");

//Pokemon json object
let POKEMON = {};

//Define pokemon types
const NORMAL = "Normal";
const FIRE = "Fire";
const WATER = "Water";
const GRASS = "Grass";
const ELECTRIC = "Electric";
const ICE = "Ice";
const FIGHTING = "Fighting";
const POISON = "Poison";
const GROUND = "Ground";
const FLYING = "Flying";
const PSYCHIC = "Psychic";
const BUG = "Bug";
const ROCK = "Rock";
const GHOST = "Ghost";
const DRAGON = "Dragon";
const DARK = "Dark";
const STEEL = "Steel";

//Updates the json data
add_gen1();
add_gen2();
add_gen3();
add_gen4();
add_pictures();
add_generations();

//Outputs new json data to new json file
let stringed = JSON.stringify(POKEMON, null, 4);
fs.writeFile("pokemon.json", stringed, "utf-8", (err) => {
    if (err) {
        throw err;
    }
    console.log("DONE");
});

function add_generations() {

}

function add_pictures() {
    for (let mon in POKEMON) {
        let num = POKEMON[mon]["number"];
        if (num < 10) {
            POKEMON[mon]["picture"] = `./Pictures/00${num}.png`;
        }
        else if (num < 100) {
            POKEMON[mon]["picture"] = `./Pictures/0${num}.png`;
        }
        else {
            POKEMON[mon]["picture"] = `./Pictures/${num}.png`;
        }
    }
}

function ap(gen, name, number, type1, type2) {
    POKEMON[name] = {
        "number": number,
        "types": [type1],
        "generation": gen
    }

    if (type2 != null) {
        POKEMON[name]["types"].push(type2);
    }
}

function add_gen1() {
    ap(1, "Bulbasaur", 1, GRASS, POISON);
    ap(1, "Ivysaur", 2, GRASS, POISON);
    ap(1, "Venusaur", 3, GRASS, POISON);
    ap(1, "Charmander", 4, FIRE);
    ap(1, "Charmeleon", 5, FIRE);
    ap(1, "Charizard", 6, FIRE, FLYING);
    ap(1, "Squirtle", 7, WATER);
    ap(1, "Wartortle", 8, WATER);
    ap(1, "Blastoise", 9, WATER);
    ap(1, "Caterpie", 10, BUG);
    ap(1, "Metapod", 11, BUG);
    ap(1, "Butterfree", 12, BUG, FLYING);
    ap(1, "Weedle", 13, BUG, POISON);
    ap(1, "Kakuna", 14, BUG, POISON);
    ap(1, "Beedrill", 15, BUG, POISON);
    ap(1, "Pidgey", 16, NORMAL, FLYING);
    ap(1, "Pidgeotto", 17, NORMAL, FLYING);
    ap(1, "Pidgeot", 18, NORMAL, FLYING);
    ap(1, "Rattata", 19, NORMAL);
    ap(1, "Raticate", 20, NORMAL);
    ap(1, "Spearow", 21, NORMAL, FLYING);
    ap(1, "Fearow", 22, NORMAL, FLYING);
    ap(1, "Ekans", 23, POISON);
    ap(1, "Arbok", 24, POISON);
    ap(1, "Pikachu", 25, ELECTRIC);
    ap(1, "Raichu", 26, ELECTRIC);
    ap(1, "Sandshrew", 27, GROUND);
    ap(1, "Sandslash", 28, GROUND);
    ap(1, "Nidoran(f)", 29, POISON);
    ap(1, "Nidorina", 30, POISON);
    ap(1, "Nidoqueen", 31, POISON, GROUND);
    ap(1, "Nidoran(m)", 32, POISON);
    ap(1, "Nidorino", 33, POISON);
    ap(1, "Nidoking", 34, POISON, GROUND);
    ap(1, "Clefairy", 35, NORMAL);
    ap(1, "Clefable", 36, NORMAL);
    ap(1, "Vulpix", 37, FIRE);
    ap(1, "Ninetales", 38, FIRE);
    ap(1, "Jigglypuff", 39, NORMAL);
    ap(1, "Wigglytuff", 40, NORMAL);
    ap(1, "Zubat", 41, POISON, FLYING);
    ap(1, "Golbat", 42, POISON, FLYING);
    ap(1, "Oddish", 43, GRASS, POISON);
    ap(1, "Gloom", 44, GRASS, POISON);
    ap(1, "Vileplume", 45, GRASS, POISON);
    ap(1, "Paras", 46, BUG, GRASS);
    ap(1, "Parasect", 47, BUG, GRASS);
    ap(1, "Venonat", 48, BUG, POISON);
    ap(1, "Venomoth", 49, BUG, POISON);
    ap(1, "Diglett", 50, GROUND);
    ap(1, "Dugtrio", 51, GROUND);
    ap(1, "Meowth", 52, NORMAL);
    ap(1, "Persian", 53, NORMAL);
    ap(1, "Psyduck", 54, WATER);
    ap(1, "Golduck", 55, WATER);
    ap(1, "Mankey", 56, FIGHTING);
    ap(1, "Primeape", 57, FIGHTING);
    ap(1, "Growlithe", 58, FIRE);
    ap(1, "Arcanine", 59, FIRE);
    ap(1, "Poliwag", 60, WATER);
    ap(1, "Poliwhirl", 61, WATER);
    ap(1, "Poliwrath", 62, WATER, FIGHTING);
    ap(1, "Abra", 63, PSYCHIC);
    ap(1, "Kadabra", 64, PSYCHIC);
    ap(1, "Alakazam", 65, PSYCHIC);
    ap(1, "Machop", 66, FIGHTING);
    ap(1, "Machoke", 67, FIGHTING);
    ap(1, "Machamp", 68, FIGHTING);
    ap(1, "Bellsprout", 69, GRASS, POISON);
    ap(1, "Weepinbell", 70, GRASS, POISON);
    ap(1, "Victreebel", 71, GRASS, POISON);
    ap(1, "Tentacool", 72, WATER, POISON);
    ap(1, "Tentacruel", 73, WATER, POISON);
    ap(1, "Geodude", 74, ROCK, GROUND);
    ap(1, "Graveler", 75, ROCK, GROUND);
    ap(1, "Golem", 76, ROCK, GROUND);
    ap(1, "Ponyta", 77, FIRE);
    ap(1, "Rapidash", 78, FIRE);
    ap(1, "Slowpoke", 79, WATER, PSYCHIC);
    ap(1, "Slowbro", 80, WATER, PSYCHIC);
    ap(1, "Magnemite", 81, ELECTRIC, STEEL);
    ap(1, "Magneton", 82, ELECTRIC, STEEL);
    ap(1, "Farfetch'd", 83, NORMAL, FLYING);
    ap(1, "Doduo", 84, NORMAL, FLYING);
    ap(1, "Dodrio", 85, NORMAL, FLYING);
    ap(1, "Seel", 86, WATER);
    ap(1, "Dewgong", 87, WATER, ICE);
    ap(1, "Grimer", 88, POISON);
    ap(1, "Muk", 89, POISON);
    ap(1, "Shellder", 90, WATER);
    ap(1, "Cloyster", 91, WATER, ICE);
    ap(1, "Gastly", 92, GHOST, POISON);
    ap(1, "Haunter", 93, GHOST, POISON);
    ap(1, "Gengar", 94, GHOST, POISON);
    ap(1, "Onix", 95, ROCK, GROUND);
    ap(1, "Drowzee", 96, PSYCHIC);
    ap(1, "Hypno", 97, PSYCHIC);
    ap(1, "Krabby", 98, WATER);
    ap(1, "Kingler", 99, WATER);
    ap(1, "Voltorb", 100, ELECTRIC);
    ap(1, "Electrode", 101, ELECTRIC);
    ap(1, "Exeggcute", 102, GRASS, PSYCHIC);
    ap(1, "Cubone", 104, GROUND);
    ap(1, "Marowak", 105, GROUND);
    ap(1, "Hitmonlee", 106, FIGHTING);
    ap(1, "Hitmonchan", 107, FIGHTING);
    ap(1, "Lickitung", 108, NORMAL);
    ap(1, "Koffing", 109, POISON);
    ap(1, "Weezing", 110, POISON);
    ap(1, "Rhyhorn", 111, GROUND, ROCK);
    ap(1, "Rhdyon", 112, GROUND, ROCK);
    ap(1, "Chansey", 113, NORMAL);
    ap(1, "Tangela", 114, GRASS);
    ap(1, "Kangaskhan", 115, NORMAL);
    ap(1, "Horsea", 116, WATER);
    ap(1, "Seadra", 117, WATER);
    ap(1, "Goldeen", 118, WATER);
    ap(1, "Seaking", 119, WATER);
    ap(1, "Staryu", 120, WATER);
    ap(1, "Starmie", 121, WATER, PSYCHIC);
    ap(1, "Mr.Mime", 122, PSYCHIC);
    ap(1, "Scyther", 123, BUG, FLYING);
    ap(1, "Jynx", 124, ICE, PSYCHIC);
    ap(1, "Electabuzz", 125, ELECTRIC);
    ap(1, "Magmar", 126, FIRE);
    ap(1, "Pinsir", 127, BUG);
    ap(1, "Tauros", 128, NORMAL);
    ap(1, "Magikarp", 129, WATER);
    ap(1, "Gyarados", 130, WATER, FLYING);
    ap(1, "Lapras", 131, WATER, ICE);
    ap(1, "Ditto", 132, NORMAL);
    ap(1, "Eevee", 133, NORMAL);
    ap(1, "Vaporeon", 134, WATER);
    ap(1, "Jolteon", 135, ELECTRIC);
    ap(1, "Flareon", 136, FIRE);
    ap(1, "Porygon", 137, NORMAL);
    ap(1, "Omanyte", 138, ROCK, WATER);
    ap(1, "Omastar", 139, ROCK, WATER);
    ap(1, "Kabuto", 140, ROCK, WATER);
    ap(1, "Kabutops", 141, ROCK, WATER);
    ap(1, "Aerodactyl", 142, ROCK, FLYING);
    ap(1, "Snorlax", 143, NORMAL);
    ap(1, "Articuno", 144, ICE, FLYING);
    ap(1, "Zapdos", 145, ELECTRIC, FLYING);
    ap(1, "Moltres", 146, FIRE, FLYING);
    ap(1, "Dratini", 147, DRAGON);
    ap(1, "Dragonair", 148, DRAGON);
    ap(1, "Dragonite", 149, DRAGON, FLYING);
    ap(1, "Mewtwo", 150, PSYCHIC);
    ap(1, "Mew", 151, PSYCHIC);
}

function add_gen2() {
    ap(2,"Chikorita", 152, GRASS);
    ap(2,"Bayleef", 153, GRASS);
    ap(2,"Meganium", 154, GRASS);
    ap(2,"Cyndaquil", 155, FIRE);
    ap(2,"Quilava", 156, FIRE);
    ap(2,"Typhlosion", 157, FIRE);
    ap(2,"Totodile", 158, WATER);
    ap(2,"Croconaw", 159, WATER);
    ap(2,"Feraligatr", 160, WATER);
    ap(2,"Sentret", 161, NORMAL);
    ap(2,"Furret", 162, NORMAL);
    ap(2,"Hoothoot", 163, NORMAL, FLYING);
    ap(2,"Noctowl", 164, NORMAL, FLYING);
    ap(2,"Ledyba", 165, BUG, FLYING);
    ap(2,"Ledian", 166, BUG, FLYING);
    ap(2,"Spinarak", 167, BUG, POISON);
    ap(2,"Ariados", 168, BUG, POISON);
    ap(2,"Crobat", 169, POISON, FLYING);
    ap(2,"Chinchou", 170, WATER, ELECTRIC);
    ap(2,"Lantern", 171, WATER, ELECTRIC);
    ap(2,"Pichu", 172, ELECTRIC);
    ap(2,"Cleffa", 173, NORMAL);
    ap(2,"Igglybuff", 174, NORMAL);
    ap(2,"Togepi", 175, NORMAL);
    ap(2,"Togetic", 176, NORMAL, FLYING);
    ap(2,"Natu", 177, PSYCHIC, FLYING);
    ap(2,"Xatu", 178, PSYCHIC, FLYING);
    ap(2,"Mareep", 179, ELECTRIC);
    ap(2,"Flaafy", 180, ELECTRIC);
    ap(2,"Ampharos", 181, ELECTRIC);
    ap(2,"Bellossom", 182, GRASS);
    ap(2,"Marill", 183, WATER);
    ap(2,"Azumarill", 184, WATER);
    ap(2,"Sudowoodo", 185, ROCK);
    ap(2,"Politoed", 186, WATER);
    ap(2,"Hoppip", 187, GRASS, FLYING);
    ap(2,"Skiploom", 188, GRASS, FLYING);
    ap(2,"Jumpluff", 189, GRASS, FLYING);
    ap(2,"Aipom", 190, NORMAL);
    ap(2,"Sunkern", 191, GRASS);
    ap(2,"Sunflora", 192, GRASS);
    ap(2,"Yanma", 193, BUG, FLYING);
    ap(2,"Wooper", 194, WATER, GROUND);
    ap(2,"Quagsire", 195, WATER, GROUND);
    ap(2,"Espeon", 196, PSYCHIC);
    ap(2,"Umbreon", 197, DARK);
    ap(2,"Murkrow", 198, DARK, FLYING);
    ap(2,"Slowking", 199, WATER, PSYCHIC);
    ap(2,"Misdreavus", 200, GHOST);
    ap(2,"Unown", 201, PSYCHIC);
    ap(2,"Wobbuffet", 202, PSYCHIC);
    ap(2,"Girafarig", 203, NORMAL, PSYCHIC);
    ap(2,"Pineco", 204, BUG);
    ap(2,"Forretress", 205, BUG, STEEL);
    ap(2,"Dunsparce", 206, NORMAL);
    ap(2,"Gligar", 207, GROUND, FLYING);
    ap(2,"Steelix", 208, STEEL, GROUND);
    ap(2,"Snubbull", 209, NORMAL);
    ap(2,"Granbull", 210, NORMAL);
    ap(2,"Qwilfish", 211, WATER, POISON);
    ap(2,"Scizor", 212, BUG, STEEL);
    ap(2,"Shuckle", 213, BUG, ROCK);
    ap(2,"Heracross", 214, BUG, FIGHTING);
    ap(2,"Sneasel", 215, DARK, ICE);
    ap(2,"Teddiursa", 216, NORMAL);
    ap(2,"Ursaring", 217, NORMAL);
    ap(2,"Slugma", 218, FIRE);
    ap(2,"Magcargo", 219, FIRE, ROCK);
    ap(2,"Swinub", 220, ICE, GROUND);
    ap(2,"Piloswine", 221, ICE, GROUND);
    ap(2,"Corsola", 222, WATER, ROCK);
    ap(2,"Remoraid", 223, WATER);
    ap(2,"Octillery", 224, WATER);
    ap(2,"Delibird", 225, ICE, FLYING);
    ap(2,"Mantine", 226, WATER, FLYING);
    ap(2,"Skarmory", 227, STEEL, FLYING);
    ap(2,"Houndour", 228, DARK, FIRE);
    ap(2,"Houndoom", 229, DARK, FIRE);
    ap(2,"Kingdra", 230, WATER, DRAGON);
    ap(2,"Phanpy", 231, GROUND);
    ap(2,"Donphan", 232, GROUND);
    ap(2,"Porygon2", 233, NORMAL);
    ap(2,"Stantler", 234, NORMAL);
    ap(2,"Smeargle", 235, NORMAL);
    ap(2,"Tyrogue", 236, FIGHTING);
    ap(2,"Hitmontop", 237, FIGHTING);
    ap(2,"Smoochum", 238, ICE, PSYCHIC);
    ap(2,"Elekid", 239, ELECTRIC);
    ap(2,"Magby", 240, FIRE);
    ap(2,"Miltank", 241, NORMAL);
    ap(2,"Blissey", 242, NORMAL);
    ap(2,"Raikou", 243, ELECTRIC);
    ap(2,"Entei", 244, FIRE);
    ap(2,"Suicune", 245, WATER);
    ap(2,"Larvitar", 246, ROCK, GROUND);
    ap(2,"Pupitar", 247, ROCK, GROUND);
    ap(2,"Tyranitar", 248, ROCK, DARK);
    ap(2,"Lugia", 249, PSYCHIC, FLYING);
    ap(2,"Ho-oh", 250, FIRE, FLYING);
    ap(2,"Celebi", 251, PSYCHIC, GRASS);
}

function add_gen3() {
    ap(3,"Treecko", 252, GRASS);
    ap(3,"Grovyle", 253, GRASS);
    ap(3,"Sceptile", 254, GRASS);
    ap(3,"Torchic", 255, FIRE);
    ap(3,"Combusken", 256, FIRE, FIGHTING);
    ap(3,"Blaziken", 257, FIRE, FIGHTING);
    ap(3,"Mudkip", 258, WATER);
    ap(3,"Marshtomp", 259, WATER, GROUND);
    ap(3,"Swampert", 260, WATER, GROUND);
    ap(3,"Poochyena", 261, DARK);
    ap(3,"Mightyena", 262, DARK);
    ap(3,"Zigzagoon", 263, NORMAL);
    ap(3,"Linoone", 264, NORMAL);
    ap(3,"Wurmple", 265, BUG);
    ap(3,"Silcoon", 266, BUG);
    ap(3,"Beautifly", 267, BUG, FLYING);
    ap(3,"Cascoon", 268, BUG);
    ap(3,"Dustox", 269, BUG, POISON);
    ap(3,"Lotad", 270, WATER, GRASS);
    ap(3,"Lombre", 271, WATER, GRASS);
    ap(3,"Ludicolo", 272, WATER, GRASS);
    ap(3,"Seedot", 273, GRASS);
    ap(3,"Nuzleaf", 274, GRASS, DARK);
    ap(3,"Shiftry", 275, GRASS, DARK);
    ap(3,"Taillow", 276, NORMAL, FLYING);
    ap(3,"Swellow", 277, NORMAL, FLYING);
    ap(3,"Wingull", 278, WATER, FLYING);
    ap(3,"Pelipper", 279, WATER, FLYING);
    ap(3,"Ralts", 280, PSYCHIC);
    ap(3,"Kirlia", 281, PSYCHIC);
    ap(3,"Gardevoir", 282, PSYCHIC);
    ap(3,"Surskit", 283, BUG, WATER);
    ap(3,"Masquerain", 284, BUG, FLYING);
    ap(3,"Shroomish", 285, GRASS);
    ap(3,"Breloom", 286, GRASS, FIGHTING);
    ap(3,"Slakoth", 287, NORMAL);
    ap(3,"Vigoroth", 288, NORMAL);
    ap(3,"Slaking", 289, NORMAL);
    ap(3,"Nincada", 290, BUG, GROUND);
    ap(3,"Ninjask", 291, BUG, FLYING);
    ap(3,"Shedinja", 292, BUG, GHOST);
    ap(3,"Whismur", 293, NORMAL);
    ap(3,"Loudred", 294, NORMAL);
    ap(3,"Exploud", 295, NORMAL);
    ap(3,"Makuhita", 296, FIGHTING);
    ap(3,"Hariyama", 297, FIGHTING);
    ap(3,"Azurill", 298, NORMAL);
    ap(3,"Nosepass", 299, ROCK);
    ap(3,"Skitty", 300, NORMAL);
    ap(3,"Delcatty", 301, NORMAL);
    ap(3,"Sableye", 302, DARK, GHOST);
    ap(3,"Mawile", 303, STEEL);
    ap(3,"Aron", 304, STEEL, ROCK);
    ap(3,"Lairon", 305, STEEL, ROCK);
    ap(3,"Aggron", 306, STEEL, ROCK);
    ap(3,"Meditite", 307, FIGHTING, PSYCHIC);
    ap(3,"Medicham", 308, FIGHTING, PSYCHIC);
    ap(3,"Electrike", 309, ELECTRIC);
    ap(3,"Manectric", 310, ELECTRIC);
    ap(3,"Plusle", 311, ELECTRIC);
    ap(3,"Minun", 312, ELECTRIC);
    ap(3,"Volbeat", 313, BUG);
    ap(3,"Illumise", 314, BUG);
    ap(3,"Roselia", 315, GRASS, POISON);
    ap(3,"Gulpin", 316, POISON);
    ap(3,"Swalot", 317, POISON);
    ap(3,"Carvanha", 318, WATER, DARK);
    ap(3,"Sharpedo", 319, WATER, DARK);
    ap(3,"Wailmer", 320, WATER);
    ap(3,"Wailord", 321, WATER);
    ap(3,"Numel", 322, FIRE, GROUND);
    ap(3,"Camerupt", 323, FIRE, GROUND);
    ap(3,"Torkoal", 324, FIRE);
    ap(3,"Spoink", 325, PSYCHIC);
    ap(3,"Grumpig", 326, PSYCHIC);
    ap(3,"Spinda", 327, NORMAL);
    ap(3,"Trapinch", 328, GROUND);
    ap(3,"Vibrava", 329, GROUND, DRAGON);
    ap(3,"Flygon", 330, GROUND, DRAGON);
    ap(3,"Cacnea", 331, GRASS);
    ap(3,"Cacturne", 332, GRASS, DARK);
    ap(3,"Swablu", 333, NORMAL, FLYING);
    ap(3,"Altaria", 334, DRAGON, FLYING);
    ap(3,"Zangoose", 335, NORMAL);
    ap(3,"Seviper", 336, POISON);
    ap(3,"Lunatone", 337, ROCK, PSYCHIC);
    ap(3,"Solrock", 338, ROCK, PSYCHIC);
    ap(3,"Barboach", 339, WATER, GROUND);
    ap(3,"Whiscash", 340, WATER, GROUND);
    ap(3,"Corphish", 341, WATER);
    ap(3,"Crawdaunt", 342, WATER, DARK);
    ap(3,"Baltoy", 343, GROUND, PSYCHIC);
    ap(3,"Claydol", 344, GROUND, PSYCHIC);
    ap(3,"Lileep", 345, ROCK, GRASS);
    ap(3,"Cradily", 346, ROCK, GRASS);
    ap(3,"Anorith", 347, ROCK, BUG);
    ap(3,"Armaldo", 348, ROCK, BUG);
    ap(3,"Feebas", 349, WATER);
    ap(3,"Milotic", 350, WATER);
    ap(3,"Castform", 351, NORMAL);
    ap(3,"Kecleon", 352, NORMAL);
    ap(3,"Shuppet", 353, GHOST);
    ap(3,"Banette", 354, GHOST);
    ap(3,"Duskull", 355, GHOST);
    ap(3,"Dusclops", 356, GHOST);
    ap(3,"Tropius", 357, GRASS, FLYING);
    ap(3,"Chimecho", 358, PSYCHIC);
    ap(3,"Absol", 359, DARK);
    ap(3,"Wynaut", 360, PSYCHIC);
    ap(3,"Snorunt", 361, ICE);
    ap(3,"Glalie", 362, ICE);
    ap(3,"SPHEAL", 363, ICE, WATER);
    ap(3,"Sealeo", 364, ICE, WATER);
    ap(3,"Walrein", 365, ICE, WATER);
    ap(3,"Clamperl", 366, WATER);
    ap(3,"Huntail", 367, WATER);
    ap(3,"Gorebyss", 368, WATER);
    ap(3,"Relicanth", 369, WATER, ROCK);
    ap(3,"Luvdisc", 370, WATER);
    ap(3,"Bagon", 371, DRAGON);
    ap(3,"Shelgon", 372, DRAGON);
    ap(3,"Salamence", 373, DRAGON, FLYING);
    ap(3,"Beldum", 374, STEEL, PSYCHIC);
    ap(3,"Metang", 375, STEEL, PSYCHIC);
    ap(3,"Metagross", 376, STEEL, PSYCHIC);
    ap(3,"Regirock", 377, ROCK);
    ap(3,"Regice", 378, ICE);
    ap(3,"Registeel", 379, STEEL);
    ap(3,"Latias", 380, DRAGON, PSYCHIC);
    ap(3,"Latios", 381, DRAGON, PSYCHIC);
    ap(3,"Kyogre", 382, WATER);
    ap(3,"Groudon", 383, GROUND);
    ap(3,"Rayquaza", 384, DRAGON, FLYING);
    ap(3,"Jirachi", 385, STEEL, PSYCHIC);
    ap(3,"Deoxys", 386, PSYCHIC);
}

function add_gen4() {
    ap(4,"Turtwig", 387, GRASS);
    ap(4,"Grotle", 388, GRASS);
    ap(4,"Tortera", 389, GRASS, GROUND);
    ap(4,"Chimchar", 390, FIRE);
    ap(4,"Monferno", 391, FIRE, FIGHTING);
    ap(4,"Infernape", 392, FIRE, FIGHTING);
    ap(4,"Piplup", 393, WATER);
    ap(4,"Prinplup", 394, WATER);
    ap(4,"Empoleon", 395, WATER, STEEL);
    ap(4,"Starly", 396, NORMAL, FLYING);
    ap(4,"Staravia", 397, NORMAL, FLYING);
    ap(4,"Staraptor", 398, NORMAL, FLYING);
    ap(4,"Bidoof", 399, NORMAL);
    ap(4,"Bibarel", 400, NORMAL, WATER);
    ap(4,"Kricketot", 401, BUG);
    ap(4,"Kricketune", 402, BUG);
    ap(4,"Shinx", 403, ELECTRIC);
    ap(4,"Luxio", 404, ELECTRIC);
    ap(4,"Luxray", 405, ELECTRIC);
    ap(4,"Budew", 406, GRASS, POISON);
    ap(4,"Roserade", 407, GRASS, POISON);
    ap(4,"Cranidos", 408, ROCK);
    ap(4,"Rampardos", 409, ROCK);
    ap(4,"Shieldon", 410, ROCK, STEEL);
    ap(4,"Bastiodon", 411, ROCK, STEEL);
    ap(4,"Burmy", 412, BUG);
    ap(4,"Wormadam", 413, BUG, GRASS);
    ap(4,"Mothim", 414, BUG, FLYING);
    ap(4,"Combee", 415, BUG, FLYING);
    ap(4,"Vespiquen", 416, BUG, FLYING);
    ap(4,"Pachirisu", 417, ELECTRIC);
    ap(4,"Buizel", 418, WATER);
    ap(4,"Floatzel", 419, WATER);
    ap(4,"Cherubi", 420, GRASS);
    ap(4,"Cherrim", 421, GRASS);
    ap(4,"Shellos", 422, WATER);
    ap(4,"Gastrodon", 423, WATER, GROUND);
    ap(4,"Ambipom", 424, NORMAL);
    ap(4,"Drifloon", 425, GHOST, FLYING);
    ap(4,"Drifblim", 426, GHOST, FLYING);
    ap(4,"Buneary", 427, NORMAL);
    ap(4,"Lopunny", 428, NORMAL);
    ap(4,"Mismagius", 429, GHOST);
    ap(4,"Honchkrow", 430, DARK, FLYING);
    ap(4,"Glameow", 431, NORMAL);
    ap(4,"Purugly", 432, NORMAL);
    ap(4,"Chingling", 433, PSYCHIC);
    ap(4,"Stunky", 434, POISON, DARK);
    ap(4,"Skuntank", 435, POISON, DARK);
    ap(4,"Bronzor", 436, STEEL, PSYCHIC);
    ap(4,"Bronzong", 437, STEEL, PSYCHIC);
    ap(4,"Bonsly", 438, ROCK);
    ap(4,"Mime Jr.", 439, PSYCHIC);
    ap(4,"Happiny", 440, NORMAL);
    ap(4,"Chatot", 441, NORMAL, FLYING);
    ap(4,"Spiritomb", 442, GHOST, DARK);
    ap(4,"Gible", 443, DRAGON, GROUND);
    ap(4,"Gabite", 444, DRAGON, GROUND);
    ap(4,"Garchomp", 445, DRAGON, GROUND);
    ap(4,"Munchlax", 446, NORMAL);
    ap(4,"Riolu", 447, FIGHTING);
    ap(4,"Lucario", 448, FIGHTING, STEEL);
    ap(4,"Hippopotas", 449, GROUND);
    ap(4,"Hippowdon", 450, GROUND);
    ap(4,"Skorupi", 451, POISON, BUG);
    ap(4,"Drapion", 452, POISON, DARK);
    ap(4,"Croagunk", 453, POISON, FIGHTING);
    ap(4,"Toxicroak", 454, POISON, FIGHTING);
    ap(4,"Carnivine", 455, GRASS);
    ap(4,"Finneon", 456, WATER);
    ap(4,"Lumineon", 457, WATER);
    ap(4,"Mantyke", 458, WATER, FLYING);
    ap(4,"Snover", 459, GRASS, ICE);
    ap(4,"Abomasnow", 460, GRASS, ICE);
    ap(4,"Weavile", 461, DARK, ICE);
    ap(4,"Magnezone", 462, ELECTRIC, STEEL);
    ap(4,"Lickilicky", 463, NORMAL);
    ap(4,"Rhyperior", 464, GROUND, ROCK);
    ap(4,"Tangrowth", 465, GRASS);
    ap(4,"Electivire", 466, ELECTRIC);
    ap(4,"Magmortar", 467, FIRE);
    ap(4,"Togekiss", 468, NORMAL, FLYING);
    ap(4,"Yanmega", 469, BUG, FLYING);
    ap(4,"Leafeon", 470, GRASS);
    ap(4,"Glaceon", 471, ICE);
    ap(4,"Gliscor", 472, GROUND, FLYING);
    ap(4,"Mamoswine", 473, ICE, GROUND);
    ap(4,"Porygon-Z", 474, NORMAL);
    ap(4,"Gallade", 475, PSYCHIC, FIGHTING);
    ap(4,"Probopass", 476, ROCK, STEEL);
    ap(4,"Dusknoir", 477, GHOST);
    ap(4,"Froslass", 478, ICE, GHOST);
    ap(4,"Rotom", 479, ELECTRIC, GHOST);
    ap(4,"Uxie", 480, PSYCHIC);
    ap(4,"Mesprit", 481, PSYCHIC);
    ap(4,"Azelf", 482, PSYCHIC);
    ap(4,"Diagla", 483, STEEL, DRAGON);
    ap(4,"Palkia", 484, WATER, DRAGON);
    ap(4,"Heatran", 485, FIRE, STEEL);
    ap(4,"Regigigas", 486, NORMAL);
    ap(4,"Giratina", 487, GHOST, DRAGON);
    ap(4,"Cresselia", 488, PSYCHIC);
    ap(4,"Phione", 489, WATER);
    ap(4,"Manaphy", 490, WATER);
    ap(4,"Darkrai", 491, DARK);
    ap(4,"Shaymin", 494, GRASS);
    ap(4,"Arceus", 493, NORMAL);
}